# Generated by Django 5.2.8 on 2025-11-23 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="A unique identifier for this endpoint (email, phone, chat_id, token, etc.)",
                        max_length=255,
                    ),
                ),
                (
                    "endpoint_type",
                    models.CharField(
                        help_text="Endpoint type (e.g. sms, email, telegram, push). ",
                        max_length=100,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower value means higher priority."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_endpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "-verified", "-is_active", "endpoint_type"],
                "unique_together": {("user", "identifier", "endpoint_type")},
            },
        ),
    ]
